import threading
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QTextEdit
from PyQt5.QtGui import QKeyEvent


from model.piece import Piece
import model.piece
from widgets.compound.stack_panels import HStack, VStack
from widgets.compound.stretch import Stretch
from widgets.my_button import AsyncBlockingButton, GuiButton
from widgets.note_widget import PartWidget
from widgets.text_box import TextBox, Label
import widgets.widget_utils as w_utils
from csound_tests.test_methods import quit_csound, start_CSOUND, beep
from utils.logger import Log, MLogger
from utils.commands.kbd_resolver import KbdResolver    
from widgets.cmd_wiring import my_wirings
from instr_logic.csd_definition import get_built_instrument
import os

# Get the current working directory

def save_file():
    content = get_built_instrument()
    current_dir = os.getcwd()
    relative = "./generated_instrument/autogenerated.csd"
    file_path = os.path.join(current_dir, relative) 
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, "w") as file:
        file.write(content)


class MyStyledWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Stacked Panels")
        self.setStyleSheet("background-color: black;")
        
    def closeEvent(self, event):
            quit_csound()
            
class MainWindow(MyStyledWindow):
    def __init__(self):
        super().__init__()
        global Log
        
        self.part_widgets = []
        self.status_bar = TextBox(read_only=True)
        self.status_bar.setFixedHeight(200)
        self.status_bar.setStyleSheet("color: white;")
        Log = MLogger(lambda msg: self.status_bar.append_log(msg))
        self.kbd_resolver = KbdResolver(my_wirings, lambda s: Log.log(s))
        
        left_pane_buttons = [
                AsyncBlockingButton("CSOUND START", start_CSOUND), 
                AsyncBlockingButton("beep", beep), 
                AsyncBlockingButton("CSOUND STOP", quit_csound),
                AsyncBlockingButton("GENERATE CSD", save_file)
                ]
        
        scores_stack = VStack(stretch=True)
        central_v_stack = VStack(
                children=[
                    GuiButton("top button", self.button_click), 
                    HStack(
                        children=[
                            VStack(fixed_width=120, 
                                   children=left_pane_buttons, 
                                   stretch=True), 
                            scores_stack],
                        spacing=0, 
                        margin=(0, 0, 0, 0)),
                    Stretch(),
                    self.status_bar]
                )
        self.setCentralWidget(central_v_stack.widget)

        self.stack_panel = scores_stack.layout
    
    def button_click(self):
        piece = model.piece.generate_sample_piece(4, 8)
        self.load_piece(piece)
        
    def resizeEvent(self, event):
        self.kbd_resolver.clear()
        size = event.size()  
        self.setWindowTitle(f"Window resized to: {size.width()} x {size.height()}")
        super().resizeEvent(event)  
    
    def load_piece(self, piece: Piece):
        w_utils.clear_layout(self.stack_panel)
        self.part_widgets.clear()
        
        for part in piece.parts:
            part_widget = PartWidget()
            part_widget.setFixedHeight(120)  
            self.stack_panel.addWidget(part_widget)
            self.part_widgets.append(part_widget)
            part_widget.staff_widget.set_bars(part.measures[:4])
            part_widget.staff_widget.update()
                
        self.stack_panel.addStretch()
        self.stack_panel.parentWidget().update()
        self.stack_panel.update()
        
    def csound_start(self):
        t1 = threading.Thread(target=start_CSOUND, args=[])
        t1.start()
    
    def keyPressEvent(self, event: QKeyEvent):
        self.kbd_resolver.accept_press(event.key(), event.isAutoRepeat())

        
    def keyReleaseEvent(self, event: QKeyEvent):
        self.kbd_resolver.accept_release(event.key(), event.isAutoRepeat())
    